env:
  browser: true
  es2021: true
  node: true
  commonjs: true
  shared-node-browser: true

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module

globals:
  Photon: writable
  app: writable
  APP_MANIFEST: writable
  PRODUCTION: writable
  $: writable

plugins:
  - react
  - '@typescript-eslint'

rules:
  'indent':
    - error
    - tab
  'linebreak-style':
    - error
    - unix
  'quotes':
    - error
    - double
  'semi':
    - error
    - always


overrides:
  - files:
      -  src/**/*.js
    rules:
      'react/display-name':
        - off
      'no-prototype-builtins':
        - off
      '@typescript-eslint/no-var-requires':
        - off
      '@typescript-eslint/explicit-module-boundary-types':
        - off
