# Used for hosting multiple sites with their own DNS name all on the same machine, which DNS name will this server bind to
remote-address: ''

# Port for the production server to listen on
port: 80

# Maximum duration in seconds that an API call can take before timing out
timeout-time: 60

# Rate limiting
rate-limit:

  # Use rate limiting at all
  use: true

  # Time in seconds for the rate limit window
  window-time: 60

  # Maximum amount of requests before rate limiting is implemented
  max-requests: 250

# SSL configuration
ssl:

  # Use SSL at all
  use: false

  # Redirect HTTP to HTTPS
  redirect: true

  # Path to the certificate root folder
  cert-root: ''

  # Port for the HTTPS server to run on
  port: 443
